// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AboutWindow() {
  return window['go']['main']['App']['AboutWindow']();
}

export function AnalyzeCSVFiles(arg1) {
  return window['go']['main']['App']['AnalyzeCSVFiles'](arg1);
}

export function ExportDataToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportDataToCSV'](arg1, arg2);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectExport() {
  return window['go']['main']['App']['SelectExport']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UpdateCheckUI() {
  return window['go']['main']['App']['UpdateCheckUI']();
}
