// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeCSVFiles(arg1:string):Promise<Array<main.EntryCount>>;

export function ExportDataToCSV(arg1:Array<main.EntryCount>,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function SelectExport():Promise<string>;

export function SelectFile():Promise<string>;
