// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AboutWindow():Promise<void>;

export function AnalyzeCSVFiles(arg1:string):Promise<Array<main.EntryCount>>;

export function ExportDataToCSV(arg1:Array<main.EntryCount>,arg2:string):Promise<void>;

export function GetCurrentVersion():Promise<string>;

export function InfoWindow(arg1:string):Promise<void>;

export function SelectExport():Promise<string>;

export function SelectFile():Promise<string>;

export function UpdateCheckUI():Promise<void>;
